<Workspace Version="1.0.0.1180" X="121.138242556443" Y="32.9695641154517" zoom="0.819249338322778" Name="bimorph.RenumberOrRenameSheets" Description="Renumber or rename Revit sheets with a list of strings. To renumber only, leave newNames input empty &#xD;&#xA;&#xD;&#xA;Sheets and newNumbers items must have an equal count to run" ID="423368c0-fef5-4d78-a5f3-e52a1a46caf3" Category="BimorphNodes.Revit.Sheets.Actions">
  <NamespaceResolutionMap>
    <ClassMap partialName="Sheet" resolvedName="Revit.Elements.Views.Sheet" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="d82ddb2e-d5f4-4ea4-937c-a34ad1c25249" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1270.8894730106" y="335.412055938625" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="4">
      <Script>#Copyright 2016. All rights reserved. Bimorph Consultancy LTD, 5 St Johns Lane, London EC1M 4BH www.bimorph.co.uk
#Written by Thomas Mahon @Thomas__Mahon info@bimorph.co.uk Package: bimorphNodes
#GitHub: https://github.com/ThomasMahon/bimorphNodes/
#Follow: facebook.com/bimorphBIM | linkedin.com/company/bimorph-bim | @bimorphBIM

import clr
clr.AddReference("RevitAPIUI")
from Autodesk.Revit.UI import TextBox
from Autodesk.Revit.UI import TaskDialog
from Autodesk.Revit.UI import TaskDialogCommonButtons

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument

def convertToList(testList):
	if isinstance(testList, list):
		return testList
	else:
		return [testList]
		
def checkInputNamesForDuplicates(newNamesList):
	if len(newNamesList) != len( set(newNamesList) ):
		TaskDialog.Show("Terminating rename process", "The list of newNumbers contains duplicates. Check your newNumbers list and ensure all new names are unique", TaskDialogCommonButtons.Ok)
		return True
		
def sheetNumbers(sheetList):
	docSheetNumbers = []
	for s in sheetList:
		docSheetNumbers.Add( s.SheetNumber )
	return docSheetNumbers
		
def renameSheet(sheets, data, param):
	for s, n in zip(sheets, data):
		numberParam = s.get_Parameter( param )
		numberParam.Set(n)
	
run = IN[3]

collector = FilteredElementCollector(doc).OfClass( ViewSheet ).OfCategory( BuiltInCategory.OST_Sheets )
elementlist = collector.ToElements()

docSheetNumbers = sheetNumbers(elementlist)

if run:
	TransactionManager.Instance.EnsureInTransaction(doc)
	
	sheets = UnwrapElement( convertToList(IN[0]) )
	newNumbers = convertToList( IN[1] )
	newNames =  convertToList( IN[2] )
	
	renameSheets = len(IN[2]) &gt; 0
	
	inputSheetNumbers = sheetNumbers(sheets)
	checkForDuplicates = checkInputNamesForDuplicates(newNumbers)
	if checkForDuplicates:
		OUT = "Rename terminated - list of new sheet names contains duplicates. Provide unique names and try again"
	else:
		if len(sheets) == len(newNumbers):
			duplicateName = []
			for i in newNumbers:
				if i in docSheetNumbers and i not in inputSheetNumbers: 
					duplicateName.Add( i )
			if len(duplicateName) &gt; 0: 
				TransactionManager.Instance.TransactionTaskDone()
				
				TaskDialog.Show("Terminating rename process", "The following sheet numbers already exist and cannot be used to re-number the sheets. Provide a list of unique names and try again:\n" + str(duplicateName), TaskDialogCommonButtons.Ok)
				OUT = "Rename terminated - new sheet names conflict with existing sheets in the document: " + str(duplicateName) + ". Provide unique names and try again" 
			else:
				renameSheet(sheets, [s.Id for s in sheets], BuiltInParameter.SHEET_NUMBER) 
				renameSheet(sheets, newNumbers, BuiltInParameter.SHEET_NUMBER) 
				
				if renameSheets:
					renameSheet(sheets, newNames, BuiltInParameter.SHEET_NAME)
				
				TransactionManager.Instance.TransactionTaskDone()
				OUT = "Sheets successfully renamed"
		else:
			TransactionManager.Instance.TransactionTaskDone()
			
			TaskDialog.Show("Lacing error", "The sheets and newNumbers lists are not equal in length. Ensure both lists contain an equal number of items and try again", TaskDialogCommonButtons.Ok)
			OUT = "Rename terminated - Lacing mismatch - ensure an equal number of items are in the sheets and newNumbers lists"</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="2b7d64c8-588b-481c-9d97-197443a69988" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="731.479185056145" y="272.534221944077" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Enter the Revit sheets to renumber or rename&#xD;&#xA;sheets:Sheet[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="2da48391-38ee-4631-919f-03cf635fcc38" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="664.489617047377" y="353.310962386608" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Enter a list of sheet numbers to renumber the sheets&#xD;&#xA;newNumbers:string[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="1410bbca-e07d-45ad-998c-6ff1ede10e3f" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="459.083920281944" y="422.721459992397" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Enter a list of sheet names to rename the sheets. Leave empty to renumber only&#xD;&#xA;newNames:string[]={}" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="3b9ccb55-2953-4a10-93bf-31c478d12d98" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="722.391800264252" y="512.23054121802" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Set to True renumber or rename the input sheets&#xD;&#xA;run:bool" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="551a9cc3-d996-4a77-8e4b-fb008485d436" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1434.30748387846" y="360.299781366454" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="report" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="d82ddb2e-d5f4-4ea4-937c-a34ad1c25249" start_index="0" end="551a9cc3-d996-4a77-8e4b-fb008485d436" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2b7d64c8-588b-481c-9d97-197443a69988" start_index="0" end="d82ddb2e-d5f4-4ea4-937c-a34ad1c25249" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2da48391-38ee-4631-919f-03cf635fcc38" start_index="0" end="d82ddb2e-d5f4-4ea4-937c-a34ad1c25249" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1410bbca-e07d-45ad-998c-6ff1ede10e3f" start_index="0" end="d82ddb2e-d5f4-4ea4-937c-a34ad1c25249" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3b9ccb55-2953-4a10-93bf-31c478d12d98" start_index="0" end="d82ddb2e-d5f4-4ea4-937c-a34ad1c25249" end_index="3" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Graph.Notes.NoteModel guid="7f936ab6-32b0-40b0-a34b-52611cd64720" text="AUTHOR + COPYRIGHT&#xD;&#xA;________________________________________________________&#xD;&#xA;&#xD;&#xA;Copyright 2016 Bimorph Consultancy &#xD;&#xA;Thomas Mahon&#xD;&#xA;@Thomas__Mahon" x="87.1501083647845" y="320.396152312152" />
    <Dynamo.Graph.Notes.NoteModel guid="b11c7c05-a4d2-4236-970c-6d807529135c" text="CONTACT&#xD;&#xA;________________________________________________________&#xD;&#xA;&#xD;&#xA;www.bimorph.co.uk&#xD;&#xA;&#xD;&#xA;info@bimorph.co.uk&#xD;&#xA;@bimorphBIM" x="86.5239727483897" y="436.208444580609" />
    <Dynamo.Graph.Notes.NoteModel guid="30526b9b-4901-4d74-bdb0-6b77c1cb7e49" text="PACKAGE NAME&#xD;&#xA;________________________________________________________&#xD;&#xA;&#xD;&#xA;bimorphNodes" x="86.4959593237265" y="235.618665594205" />
    <Dynamo.Graph.Notes.NoteModel guid="169ce30b-1d36-4169-9727-795d4ace0d9d" text="GITHUB&#xD;&#xA;________________________________________________________&#xD;&#xA;&#xD;&#xA;To report bugs or suggest improvements or new features, visit:&#xD;&#xA;&#xD;&#xA;https://github.com/ThomasMahon/bimorphNodes/" x="87.448503550683" y="731.254625566359" />
    <Dynamo.Graph.Notes.NoteModel guid="1313c5c3-6695-456d-9f0e-c10cf6a06461" text="FOLLOW US&#xD;&#xA;________________________________________________________&#xD;&#xA;&#xD;&#xA;Follow us to get the latest news on bimorph digital engineering and updates to bimorphNodes:&#xD;&#xA;&#xD;&#xA;FACEBOOK:  facebook.com/bimorphBIM&#xD;&#xA;LINKEDIN:  linkedin.com/company/bimorph-bim&#xD;&#xA;TWITTER:  @bimorphBIM" x="86.6029624963006" y="567.264654651849" />
  </Notes>
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="d504c94e-f102-4749-b5b2-15bb00a15a6c" annotationText="NODE DETAILS" left="76.4959593237265" top="182.285332260872" width="319.619210893623" height="679.635959972155" fontSize="36" InitialTop="235.618665594205" InitialHeight="635.635959972155" TextblockHeight="43.3333333333333" backgrouund="#FFD8D8D8">
      <Models ModelGuid="7f936ab6-32b0-40b0-a34b-52611cd64720" />
      <Models ModelGuid="b11c7c05-a4d2-4236-970c-6d807529135c" />
      <Models ModelGuid="30526b9b-4901-4d74-bdb0-6b77c1cb7e49" />
      <Models ModelGuid="169ce30b-1d36-4169-9727-795d4ace0d9d" />
      <Models ModelGuid="1313c5c3-6695-456d-9f0e-c10cf6a06461" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>