<Workspace Version="1.0.0.1180" X="747.475160501878" Y="291.623868511217" zoom="0.752633033731266" Name="bimorph.CADLayersInUse" Description="Get the list of layer names from a CAD link or import that are in use and contain curves" ID="3782f978-48c2-4a36-bb8f-abe01599c833" Category="BimorphNodes.DWG  |  DGN.Query">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="6cf618ed-b93d-484e-a8e0-8a499ad32a12" type="PythonNodeModels.PythonNode" nickname="Python Script" x="204.537488490536" y="-45.4625115094643" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>#Copyright 2016. All rights reserved. Bimorph Consultancy LTD, 5 St Johns Lane, London EC1M 4BH www.bimorph.co.uk
#Written by Thomas Mahon @Thomas__Mahon info@bimorph.co.uk Package: bimorphNodes
#GitHub: https://github.com/ThomasMahon/bimorphNodes/
#Follow: facebook.com/bimorphBIM | linkedin.com/company/bimorph-bim | @bimorphBIM

import clr

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument

importDWG = UnwrapElement(IN[0])

geomEnum = importDWG.Geometry[ Options() ].GetEnumerator()

failedFilter = []
layerList = []
while geomEnum.MoveNext(): 
	instGeom = geomEnum.Current.GetInstanceGeometry()
	
	instGeomEnum = instGeom.GetEnumerator()
	while instGeomEnum.MoveNext():
		e = instGeomEnum.Current
		try:
			graphicStyleId = e.GraphicsStyleId
					
			eleGraphicStyle = doc.GetElement(graphicStyleId)
			eleGraphicStyleName = eleGraphicStyle.GraphicsStyleCategory.Name
			
			layerList.Add(eleGraphicStyleName)
			
		except:
			try:
				vol = e.Volume
				
				if vol == 0.0:
					edgesList = e.Edges
					edgesEnum = edgesList.GetEnumerator()

					while edgesEnum.MoveNext():
						edge = edgesEnum.Current
						eleGraphicStyle = doc.GetElement(edge.GraphicsStyleId)
						eleGraphicStyleName = eleGraphicStyle.GraphicsStyleCategory.Name
						
						layerList.Add(eleGraphicStyleName)
						break	
			except:
				failedFilter.Add(e)
	
OUT = set(layerList)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="896b2b30-6e21-481d-b7c8-6aa656c914a9" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-347.117515700645" y="-47.7508133099397" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Input the ImportInstance to find layers that are in use&#xD;&#xA;importInstance" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="0f0d9e8a-2826-4f38-b1d3-fd5590072570" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="352.531678902561" y="-42.2344242368922" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="layerNames" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="6cf618ed-b93d-484e-a8e0-8a499ad32a12" start_index="0" end="0f0d9e8a-2826-4f38-b1d3-fd5590072570" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="896b2b30-6e21-481d-b7c8-6aa656c914a9" start_index="0" end="6cf618ed-b93d-484e-a8e0-8a499ad32a12" end_index="0" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Graph.Notes.NoteModel guid="ff1c113e-e9f8-4e74-94b6-edee2d7f8e19" text="AUTHOR + COPYRIGHT&#xD;&#xA;________________________________________________________&#xD;&#xA;&#xD;&#xA;Copyright 2016 Bimorph Consultancy &#xD;&#xA;Thomas Mahon&#xD;&#xA;@Thomas__Mahon" x="-703.215877144559" y="-32.018531036055" />
    <Dynamo.Graph.Notes.NoteModel guid="bbda360d-c778-406d-a83c-7d7e98e63fe7" text="CONTACT&#xD;&#xA;________________________________________________________&#xD;&#xA;&#xD;&#xA;www.bimorph.co.uk&#xD;&#xA;&#xD;&#xA;info@bimorph.co.uk&#xD;&#xA;@bimorphBIM" x="-703.842012760954" y="83.7937612324029" />
    <Dynamo.Graph.Notes.NoteModel guid="d4fb9f11-1932-4018-8deb-b304b4674ea8" text="PACKAGE NAME&#xD;&#xA;________________________________________________________&#xD;&#xA;&#xD;&#xA;bimorphNodes" x="-703.870026185617" y="-116.796017754002" />
    <Dynamo.Graph.Notes.NoteModel guid="6c75b8db-9756-4698-b6d6-7acc53d5e67b" text="GITHUB&#xD;&#xA;________________________________________________________&#xD;&#xA;&#xD;&#xA;To report bugs or suggest improvements or new features, visit:&#xD;&#xA;&#xD;&#xA;https://github.com/ThomasMahon/bimorphNodes/" x="-702.91748195866" y="378.839942218153" />
    <Dynamo.Graph.Notes.NoteModel guid="7c2b6ea3-c416-4366-a3a2-d068d6218bc1" text="FOLLOW US&#xD;&#xA;________________________________________________________&#xD;&#xA;&#xD;&#xA;Follow us to get the latest news on bimorph digital engineering and updates to bimorphNodes:&#xD;&#xA;&#xD;&#xA;FACEBOOK:  facebook.com/bimorphBIM&#xD;&#xA;LINKEDIN:  linkedin.com/company/bimorph-bim&#xD;&#xA;TWITTER:  @bimorphBIM" x="-703.763023013043" y="214.849971303643" />
  </Notes>
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="c5bcf73c-83cd-43b5-ad17-34a47392303c" annotationText="NODE DETAILS" left="-713.870026185617" top="-170.129351087335" width="319.619210893623" height="679.635959972154" fontSize="36" InitialTop="-116.796017754002" InitialHeight="635.635959972155" TextblockHeight="43.3333333333333" backgrouund="#FFD8D8D8">
      <Models ModelGuid="ff1c113e-e9f8-4e74-94b6-edee2d7f8e19" />
      <Models ModelGuid="bbda360d-c778-406d-a83c-7d7e98e63fe7" />
      <Models ModelGuid="d4fb9f11-1932-4018-8deb-b304b4674ea8" />
      <Models ModelGuid="6c75b8db-9756-4698-b6d6-7acc53d5e67b" />
      <Models ModelGuid="7c2b6ea3-c416-4366-a3a2-d068d6218bc1" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>