<Workspace Version="1.0.0.1180" X="784.602720528008" Y="303.585289644632" zoom="0.960233205802177" Name="CADLayersInUse" Description="Get the list of layer names from a CAD link or import that are in use and contain curves" ID="3782f978-48c2-4a36-bb8f-abe01599c833" Category="BimorphNodes.DWG  |  DGN.Query">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="6cf618ed-b93d-484e-a8e0-8a499ad32a12" type="PythonNodeModels.PythonNode" nickname="Python Script" x="204.537488490536" y="-45.4625115094643" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>#Copyright 2016. All rights reserved. Bimorph Consultancy LTD, 5 St Johns Lane, London EC1M 4BH www.bimorph.co.uk
#Written by Thomas Mahon @Thomas__Mahon info@bimorph.co.uk package: bimorphNodes
#GitHub: https://github.com/ThomasMahon/bimorphNodes/

import clr

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument

importDWG = UnwrapElement(IN[0])

geomEnum = importDWG.get_Geometry(Options()).GetEnumerator()

failedFilter = []
layerList = []
while geomEnum.MoveNext(): 
	instGeom = geomEnum.Current.GetInstanceGeometry()
	
	instGeomEnum = instGeom.GetEnumerator()
	while instGeomEnum.MoveNext():
		e = instGeomEnum.Current
		try:
			graphicStyleId = e.GraphicsStyleId
					
			eleGraphicStyle = doc.GetElement(graphicStyleId)
			eleGraphicStyleName = eleGraphicStyle.GraphicsStyleCategory.Name
			
			layerList.Add(eleGraphicStyleName)
			
		except:
			try:
				vol = e.Volume
				
				if vol == 0.0:
					edgesList = e.Edges
					edgesEnum = edgesList.GetEnumerator()

					while edgesEnum.MoveNext():
						edge = edgesEnum.Current
						eleGraphicStyle = doc.GetElement(edge.GraphicsStyleId)
						eleGraphicStyleName = eleGraphicStyle.GraphicsStyleCategory.Name
						
						layerList.Add(eleGraphicStyleName)
						break	
			except:
				failedFilter.Add(e)
	
OUT = set(layerList)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="896b2b30-6e21-481d-b7c8-6aa656c914a9" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-347.117515700645" y="-47.7508133099397" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Input the ImportInstance to find layers that are in use&#xD;&#xA;importInstance" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="0f0d9e8a-2826-4f38-b1d3-fd5590072570" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="352.531678902561" y="-42.2344242368922" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <Symbol value="layerNames" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="6cf618ed-b93d-484e-a8e0-8a499ad32a12" start_index="0" end="0f0d9e8a-2826-4f38-b1d3-fd5590072570" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="896b2b30-6e21-481d-b7c8-6aa656c914a9" start_index="0" end="6cf618ed-b93d-484e-a8e0-8a499ad32a12" end_index="0" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Graph.Notes.NoteModel guid="52cf7764-f423-4fe0-be21-9a4e1730442c" text="AUTHOR&#xD;&#xA;________________________________________________________&#xD;&#xA;&#xD;&#xA;Copyright 2016 Thomas Mahon&#xD;&#xA;@Thomas__Mahon" x="-725.172883934794" y="52.1642264918196" />
    <Dynamo.Graph.Notes.NoteModel guid="b5e275f5-8b57-4208-a65f-c906d3617be8" text="CONTACT&#xD;&#xA;________________________________________________________&#xD;&#xA;&#xD;&#xA;www.bimorph.co.uk&#xD;&#xA;&#xD;&#xA;info@bimorph.co.uk&#xD;&#xA;@bimorphBIM" x="-725.035108819726" y="162.13835393414" />
    <Dynamo.Graph.Notes.NoteModel guid="25511abb-a102-4aed-b981-c8546b98e356" text="PACKAGE NAME&#xD;&#xA;________________________________________________________&#xD;&#xA;&#xD;&#xA;bimorphNodes" x="-723.981849668697" y="-32.1519643993385" />
    <Dynamo.Graph.Notes.NoteModel guid="6cbdad4b-6331-462c-b4dd-71b9b52eb420" text="GITHUB&#xD;&#xA;________________________________________________________&#xD;&#xA;&#xD;&#xA;https://github.com/ThomasMahon/bimorphNodes/" x="-723.21288901815" y="296.428672267619" />
  </Notes>
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="34dd6f5e-3526-42be-a1f5-cd11cf92aac2" annotationText="NODE DETAILS" left="-735.172883934794" top="-85.4852977326718" width="320.626661583311" height="469.247303333624" fontSize="36" InitialTop="-32.1519643993385" InitialHeight="468.580636666957" TextblockHeight="43.3333333333333" backgrouund="#FFD8D8D8">
      <Models ModelGuid="52cf7764-f423-4fe0-be21-9a4e1730442c" />
      <Models ModelGuid="b5e275f5-8b57-4208-a65f-c906d3617be8" />
      <Models ModelGuid="25511abb-a102-4aed-b981-c8546b98e356" />
      <Models ModelGuid="6cbdad4b-6331-462c-b4dd-71b9b52eb420" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>